name: adaptive_screen_utils
description: "Flutter Package for creating adaptive UIs for different screen sizes."
version: 2.4.0
homepage: https://ravikovind.github.io/
repository: https://github.com/ravikovind/adaptive_screen_utils
issue_tracker: https://github.com/ravikovind/adaptive_screen_utils/issues

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

topics:
  - sizer
  - adaptive
  - responsive
  - adaptive-screen-utils
  - flutter
